### PR TITLE
Abstract repository

### PR DESCRIPTION
**Pull request by AlejoTorres2001**
# Hi Jon! 👋🏼 
**I've been following your microservices series on youtube and so far it has been an amazing experience, keep up with the quality content!** 🚀 

Here is something I want to share with you and your audience, *an Implementation of an abstract Repository Pattern in NestJs*.
 I've been using it at work and on personal side-projects and it has proven to be reasonably competent, it Helped me to de-couple my business logic from my data layer.
I've taken the initiative to make this PR where I added it to your code base and implement it around your ````UserEntity````. I would like your feedback, as a Software Engineer, on it. 

### Brief Explanation:
- ````BaseInterfaceRepository````: Defines the signature for all of the data-layer methods available inside the repository
- ````BaseAbstractRepository````: Uses the power of Ts Generics to implement those methods using an existing ORM's Repository
**This means only the ````BaseAbstractRepository```` is coupled to the ORM implementation, this makes changing the ORM reasonably easy and it hides data-related details from Services, which will only be responsible for the business logic** 
- To implement this abstract class we will create an interface that extends ````BaseInterfaceRepository````. an example of this is the ````UserEntity```` implementation called ````UserRepositoryInterface````. Here you would be able to define Entity specific methods related to the data layer that were not included in the Abstract Repository
- Finally, we would create an Entity-specific Repository, like ````UsersRepository```` extending ````BaseAbstractRepository```` and implementing ````UserRepositoryInterface````

To use this repository inside services we will declare them as ````Providers```` inside the desired module and inject it into the services

### Things I've Done in this PR:
- Added an Implementation of an abstract Repository Pattern
- Implemented the Pattern around the UserEntity
- Added a ````SharedServiceInterface```` for ````SharedService````

### Final Notes
 - Please feel free to use any of this code in your videos I would love to see a video of you talking about this topic.
- Also, if it is of help you can check [this](https://github.com/AlejoTorres2001/actors-movies-graph/tree/master/backend) where I've been using this pattern more widely.
- Don't hesitate in asking for any changes, I'm more than willing to collaborate with you! 😄

### CODE REVIEW

**Comment by Jon-Peppinck** [comment]
> # Hi Jon! 👋🏼
> **I've been following your microservices series on youtube and so far it has been an amazing experience, keep up with the quality content!** 🚀
> 
> Here is something I want to share with you and your audience, _an Implementation of an abstract Repository Pattern in NestJs_. I've been using it at work and on personal side-projects and it has proven to be reasonably competent, it Helped me to de-couple my business logic from my data layer. I've taken the initiative to make this PR where I added it to your code base and implement it around your `UserEntity`. I would like your feedback, as a Software Engineer, on it.
> 
> ### Brief Explanation:
> * `BaseInterfaceRepository`: Defines the signature for all of the data-layer methods available inside the repository
> * `BaseAbstractRepository`: Uses the power of Ts Generics to implement those methods using an existing ORM's Repository
>   **This means only the `BaseAbstractRepository` is coupled to the ORM implementation, this makes changing the ORM reasonably easy and it hides data-related details from Services, which will only be responsible for the business logic**
> * To implement this abstract class we will create an interface that extends `BaseInterfaceRepository`. an example of this is the `UserEntity` implementation called `UserRepositoryInterface`. Here you would be able to define Entity specific methods related to the data layer that were not included in the Abstract Repository
> * Finally, we would create an Entity-specific Repository, like `UsersRepository` extending `BaseAbstractRepository` and implementing `UserRepositoryInterface`
> 
> To use this repository inside services we will declare them as `Providers` inside the desired module and inject it into the services
> 
> ### Things I've Done in this PR:
> * Added an Implementation of an abstract Repository Pattern
> * Implemented the Pattern around the UserEntity
> * Added a `SharedServiceInterface` for `SharedService`
> 
> ### Final Notes
> * Please feel free to use any of this code in your videos I would love to see a video of you talking about this topic.
> * Also, if it is of help you can check [this](https://github.com/AlejoTorres2001/actors-movies-graph/tree/master/backend) where I've been using this pattern more widely.
> * Don't hesitate in asking for any changes, I'm more than willing to collaborate with you! 😄

Dear Alejo @AlejoTorres2001 ,

Sorry for the delays in my response. I am just coming back from a 2 week leave. The 2 latest videos in the series were pre-planned, and other than making those two videos, I spent my time enjoying time with family and friends. I Hope you had a fantastic holiday! 

Thanks so much for taking the initiative to share the abstract repo pattern with me. It is a very clever idea and would love to record a video tomorrow to share with my YouTube audience.

I checked out your profile and was very impressed! I would definitely be keen to collaborate with you more on this project if that is of interest to you. Also happy to give you and/or your (coding) website a shoutout. 

The big features I'm planning on building out are:

1. Online presence
2. Chat
3. Video Calls

I have done some work relating to WebSockets (SocketIO) to create a chat application in NestJS before. Although, I want to make it more sophisticated (compared to the LinkedIn Clone playlist) by adding Redis to cache messages.

Still in the process of figuring out online presence and video calls. I had a look on your GH and saw you have done some work with WebRTC and peerjs and was wondering what your thoughts are on this library and on approaching video calls in general.

Thanks again for contributing to this project. Would love to collaborate with you further on this project if you get the time. Please feel free to share a PR on any topic at all that interest you if you get the time.


Cheers!
Jon

**Comment by AlejoTorres2001** [comment]
Thanks for replying @Jon-Peppinck , I'm having a wonderful holiday!
I'm really looking forward to your next video 🚀 . It would be great if you could give me a little shoutout. I'm moving to Madrid in a couple of weeks, I'm looking for a new job and it might help me find it. 🙏🏼 

I'm going to take a look at those features you've mentioned, although I've worked with full-duplex connections, I've never used the NestJs wrapper so I'm going to start by taking a look a the docs 📝 .

Regarding [PeerJs](https://github.com/peers/peerjs), it is my go-to wrapper for WebRTC these days. Its API is complete and covers most use cases. you can check on [Simple peer](https://github.com/feross/simple-peer) as well but I think it hasn't been updated recently.
I'll let you know if I find or come up with something useful.
Happy coding! 💻

**Comment by Jon-Peppinck** [comment]
> Thanks for replying @Jon-Peppinck , I'm having a wonderful holiday! I'm really looking forward to your next video 🚀 . It would be great if you could give me a little shoutout. I'm moving to Madrid in a couple of weeks, I'm looking for a new job and it might help me find it. 🙏🏼
> 
> I'm going to take a look at those features you've mentioned, although I've worked with full-duplex connections, I've never used the NestJs wrapper so I'm going to start by taking a look a the docs 📝 .
> 
> Regarding [PeerJs](https://github.com/peers/peerjs), it is my go-to wrapper for WebRTC these days. Its API is complete and covers most use cases. you can check on [Simple peer](https://github.com/feross/simple-peer) as well but I think it hasn't been updated recently. I'll let you know if I find or come up with something useful. Happy coding! 💻

@AlejoTorres2001 That's great to hear you are enjoying your holiday. How exciting! Hope you are able to find a new job and you have a smooth transition into the new location. I have just finished recording the video and have featured you in it - so hopefully that will help out. Should be on YouTube in a couple of days after it gets edited. Thanks so much for sharing. PeerJS sounds like a great library. Will also need to investigate further in the coming month or so. Best of luck with everything! Will ping you when the new video is out. Cheers!

**Comment by Jon-Peppinck** [comment]
> > Thanks for replying @Jon-Peppinck , I'm having a wonderful holiday! I'm really looking forward to your next video 🚀 . It would be great if you could give me a little shoutout. I'm moving to Madrid in a couple of weeks, I'm looking for a new job and it might help me find it. 🙏🏼
> > I'm going to take a look at those features you've mentioned, although I've worked with full-duplex connections, I've never used the NestJs wrapper so I'm going to start by taking a look a the docs 📝 .
> > Regarding [PeerJs](https://github.com/peers/peerjs), it is my go-to wrapper for WebRTC these days. Its API is complete and covers most use cases. you can check on [Simple peer](https://github.com/feross/simple-peer) as well but I think it hasn't been updated recently. I'll let you know if I find or come up with something useful. Happy coding! 💻
> 
> @AlejoTorres2001 That's great to hear you are enjoying your holiday. How exciting! Hope you are able to find a new job and you have a smooth transition into the new location. I have just finished recording the video and have featured you in it - so hopefully that will help out. Should be on YouTube in a couple of days after it gets edited. Thanks so much for sharing. PeerJS sounds like a great library. Will also need to investigate further in the coming month or so. Best of luck with everything! Will ping you when the new video is out. Cheers!

Just released the new video: https://youtu.be/QVOknvmfV-Y

**Comment by premdasvm** [comment]
@Jon-Peppinck @AlejoTorres2001 

Thank you for sharing your knowledge. However, I do have a question regarding transactions. How would you go about handling them?

**Comment by AlejoTorres2001** [comment]
That is a great question, I do not have much experience working with ACID compliant transactions with microservices but im pretty sure there is a solution out there, probably using rotative tokens.

Im currently taking a service-oriented architectures course in college, maybe I can ask my professor more about it

I will let you know

**Comment by premdasvm** [comment]
@AlejoTorres2001 

Thanks for getting back to me! I really appreciate it. Looking forward to hearing what your professor has to say.

**Pull request merged**
